c_compiler:             # [win]
  - vs2022              # [win]
cxx_compiler:           # [win]
  - vs2022              # [win]
c_compiler_version:     # [osx]
  - 15                  # [osx]
cxx_compiler_version:   # [osx]
  - 15                  # [osx]

c_stdlib_version:       # [osx and x86_64]
  - 10.14               # [osx and x86_64]

github_actions_labels:
- cirun-openstack-cpu-large
