pywin32:               # [win]
  - 225                # [win]
MACOSX_SDK_VERSION:    # [osx and x86_64]
  - 10.12              # [osx and x86_64]
c_compiler_version:    # [osx]
  - 15                 # [osx]
cxx_compiler_version:  # [osx]
  - 15                 # [osx]
github_actions_labels:
- cirun-openstack-cpu-large
