c_compiler:             # [win]
  - clang               # [win]
cxx_compiler:           # [win]
  - clangxx             # [win]

c_stdlib_version:       # [osx and x86_64]
  # for aligned_alloc support
  - 10.15               # [osx and x86_64]

github_actions_labels:
- cirun-openstack-cpu-xlarge
