{% set version = "7.0.4" %}

package:
  name: mongodb
  version: {{ version }}

source:
  url: https://github.com/mongodb/mongo/archive/refs/tags/r{{ version }}.tar.gz
  sha256: a70383a23e4013e9138056b1545b4360ca68eb2efbd2ba616eb0f12e8500e621
  patches:
    - patches/0001-aligned_alloc-in-libC-is-only-available-in-glibc-2.1.patch
    - patches/0002-Fix-icu-namespace-extension-for-un-vendored-icu.patch
    - patches/0003-Restore-ability-to-use-use-system-abseil-cpp.patch
    - patches/0004-Make-SCons-inherit-environment-vars.patch
    - patches/0005-Disable-fsized-deallocation-on-macOS.patch
    - patches/0006-Relax-minimum-Darwin-version-check-to-10.9.patch
    - patches/0007-Use-platform-specific-TimeStamp-implementation.patch
    - patches/0008-Fix-openssl-1.1.x-library-names-on-Windows.patch
    - patches/0009-Fix-icu-library-names-for-Windows.patch
    - patches/0010-Don-t-force-disable-auto-linking-if-use-system-boost.patch
    - patches/0011-MSVC-Don-t-generating-debug-info-forcefully.patch
    - patches/0012-Revert-SERVER-62501-Use-MSVS-2022-by-default-and-req.patch
    - patches/0013-Disable-installer-on-Windows.patch
    - patches/0014-Disable-aligned-allocation-on-macOS.patch
    - patches/0015-Drop-strict-python-pkgs-requirements-check.patch
    - patches/0016-Don-t-inject-ICU-Macros-if-using-pre-compiled-librar.patch
    - patches/0017-use-same-discovery-mechanism-for-system-boost-on-win.patch
    - patches/0018-only-use-mongo_tooling_metrics-when-building-metrics.patch

build:
  number: 0
  # times out hopelessly ([2401+2/4489] after 6h)
  skip: true  # [win]
  # currently broken w.r.t. clang/libcxx
  skip: true  # [osx]
  # debug
  skip: true  # [not linux64]
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python 3.10.*
    - ninja
    - cheetah3
    - packaging
    - regex
    - requirements-parser
    - setuptools
    - pymongo >=3.9
    - psutil
    - pyyaml >=3.0
  host:
    - libabseil
    - libboost-devel
    - icu
    # Windows build uses WinHTTP
    - libcurl  # [not win]
    # MacOS uses 'Secure Transport'
    # Windows uses 'SChannel'
    - openssl  # [linux]
    - pcre2
    - snappy
    - yaml-cpp
    - zlib
    - zstd
  run:
    - {{ pin_compatible('icu', max_pin='x') }}
    - {{ pin_compatible('yaml-cpp', max_pin='x.x.x') }}

test:
  commands:
    - mongod --help
    - mongod --version

about:
  home: http://www.mongodb.org/
  license: SSPL-1.0
  license_file:
    - LICENSE-Community.txt
     # fmt can be unvendored after upgrading to >=4.3.3
     # xref: https://github.com/mongodb/mongo/commit/eacfb9c5
    - src/third_party/fmt/dist/LICENSE.rst
     # Part of boost, but requires code changes to unvendor the dep or
     # packaging asio as a separate package
    - src/third_party/asio-master/asio/LICENSE_1_0.txt
     # Can be unvendored, needs to be packaged
    - {{ RECIPE_DIR }}/libstemmer_COPYING
     # IMO, this one is okay, it isn't used anywhere but mongodb
    - src/third_party/wiredtiger/LICENSE
     # Can be packaged
    - src/third_party/IntelRDFPMathLib20U1/eula.txt
     # This one is a discontinued project
    - src/third_party/kms-message/COPYING
    - src/third_party/kms-message/THIRD_PARTY_NOTICES
     # Can be packaged, but build system doesn't have --system flag for it
    - src/third_party/s2/LICENSE-2.0.txt
     # A consolidated version for all 3rd party with SHAs and license names
     # (Not all of them are statically linked)
    - README.third_party.md
  summary: A next-gen database that lets you do things you could never do before
  description: |
    MongoDB is an open-source, document database designed for ease of
    development and scaling.
  doc_url: https://docs.mongodb.org/manual/
  dev_url: https://github.com/mongodb/mongo

extra:
  recipe-maintainers:
    - nehaljwani
