conda_forge_output_validation: true
build_platform:
  linux_ppc64le: linux_64
  linux_aarch64: linux_64
azure:
  settings_win:
    pool:
      vmImage: windows-2019
conda_build:
  pkg_format: '2'
test: native_and_emulated
